fixup commit for tag 'MonetDB_4-9-3'

diff --git a/template/bootstrap b/template/bootstrap
--- a/template/bootstrap
+++ b/template/bootstrap
@@ -13,7 +13,7 @@
 # The Original Code is the MonetDB Database System.
 #
 # The Initial Developer of the Original Code is CWI.
-# Portions created by CWI are Copyright (C) 1997-2005 CWI.
+# Portions created by CWI are Copyright (C) 1997-2006 CWI.
 # All Rights Reserved.
 
 #
@@ -26,17 +26,17 @@
 # this is not meant to go into the distributions
 
 
-if [ -x src/utils/autogen/autogen.py ] ; then
-	AUTOGEN=src/utils/autogen/autogen.py 
+if [ -f conf/monet.m4 ]; then
+	# we're bootstrapping MonetDB itself
 	CONFDIR=
- else
-	if [ -z "$MONETDB_PREFIX" -a -n "$MONETDIST" ] ; then
-		MONETDB_PREFIX=$MONETDIST
+else
+	# we're bootstrapping one of the other packages
+	if [ -z "$MONETDB_PREFIX" -a -n "$MONETDIST" ]; then
+		MONETDB_PREFIX="$MONETDIST"
 	fi
 	if [ "$MONETDB_PREFIX" = "" ]; then
 		type -p monetdb-config > /dev/null 2>&1
-		ERROR=$?
-		if [ $ERROR -eq 0 ]; then
+		if [ $? -eq 0 ]; then
 			MONETDB_PREFIX="`monetdb-config --prefix`"
 		else
 			echo "!ERROR: requires MONETDB_PREFIX to be set or monetdb-config in your PATH"
@@ -49,8 +49,22 @@ if [ -x src/utils/autogen/autogen.py ] ; then
 	export MONETDB_INCLUDEDIR="`$MONETDB_PREFIX/bin/monetdb-config --pkgincludedir`"
 	export MONETDB_INCS="`$MONETDB_PREFIX/bin/monetdb-config --includes`"
 
-	AUTOGEN=$MONETDB_PREFIX/lib/autogen/autogen.py
 	CONFDIR="-I `$MONETDB_PREFIX/bin/monetdb-config --pkgdatadir`/conf"
+fi
+
+AUTOGEN=`type -p autogen.py`
+if [ "$AUTOGEN" -a -x "$AUTOGEN" ]; then
+	# autogen.py was properly installed and found
+	:
+elif [ -x src/utils/autogen/autogen.py ] ; then
+	# old MonetDB version (autogen.py still available)
+	AUTOGEN=src/utils/autogen/autogen.py 
+else
+	AUTOGEN=$MONETDB_PREFIX/lib/autogen/autogen.py
+	if [ ! -x "$AUTOGEN" ]; then
+		echo "!ERROR: requires autogen.py to be available"
+		exit 1
+	fi
 fi
 
 if [ "`uname`" = Darwin  -a  "`type -p glibtool 2>/dev/null`"  -a  "`type -p glibtoolize 2>/dev/null`" ] ; then
@@ -160,7 +174,7 @@ elif [ "$_PY_VERSION" -lt "$_REQ_PY_VERSION" ]; then
 fi
 
 
-$AUTOGEN `pwd` $_AM_VERSION
+$AUTOGEN `pwd` $_AM_VERSION || exit 1
 
 rm -f acconfig.h
 cp configure.ag configure.in
@@ -170,7 +184,7 @@ cat acout.in  >> configure.in
 echo ")" >> configure.in
 
 
-$LIBTOOLIZE -c -f
+$LIBTOOLIZE -c -f || exit 1
 
 # default deplibs_check_method (pass all libs)
 # needed since deplibs is switched off in libtool 1.3c (we cannot wait for 1.4)
@@ -193,14 +207,18 @@ if [ -d "$d" ] ; then
 	PKG_M4_DIR="-I $d"
 fi
 
-aclocal -I . -I conf $LT_M4_DIR $PKG_M4_DIR $CONFDIR
+aclocal -I . -I conf $LT_M4_DIR $PKG_M4_DIR $CONFDIR || exit 1
+
+# patch aclocal.m4 to "de-force" Uninx V7 tar format with `make dist`,
+# since we do have filenames/-paths longer than 99 characters.
+perl -i -p -e 's| chof | chf |g' aclocal.m4
 
 # patch aclocal.m4 to call the linker with "-IPA" on IRIX (medusa)
 # (just adding -IPA to LDFLAGS somehow doesn't help ...)
 perl -i -p -e 's|(LD-ld. )|$1-IPA |g' aclocal.m4
 
 # patch aclocal.m4 for cygpath on CYGWIN
-grep -q '"$CYGPATH_W"' aclocal.m4 && cat << "EOF" | patch aclocal.m4
+grep '"$CYGPATH_W"' aclocal.m4 >/dev/null && cat << "EOF" | patch aclocal.m4
 --- aclocal.m4.ORG      2004-09-07 18:32:18.593750000 +0200
 +++ aclocal.m4  2004-09-07 18:34:05.453125000 +0200
 @@ -6386,11 +6386,14 @@
@@ -298,11 +316,11 @@ EOF
 fi # [ "$_AM_VERSION" -lt "$_NEW_AM_VERSION" ]
 
 
-autoheader
-automake -a -c --foreign
+autoheader || exit 1
+automake -a -c --foreign || exit 1
 
-#autoupdate
-autoconf
+#autoupdate || exit 1
+autoconf || exit 1
 
 
 exit 0
