Another pass over the maintenance scripts. It has been prepared to produce an ascii SQL dump instead of a tarball

diff --git a/MonetDB5/src/tools/mchkpnt b/MonetDB5/src/tools/mchkpnt
--- a/MonetDB5/src/tools/mchkpnt
+++ b/MonetDB5/src/tools/mchkpnt
@@ -21,6 +21,7 @@ function usage()
 {
 	echo "Usage: mchkpnt [options] "
 	echo "    --dbname=<database_name>"
+	echo "    --ascii=<yes/no> default no"
 	echo "    --chkpnt=<directory>"
 	echo "    --help"
 }
@@ -46,12 +47,16 @@ fi
 
 # massage the argument list to prepare for calling
 DBNAME=""
+ASCII="no"
 while [ $# -gt 0 ]
 do
 	case "$1" in
 	 "--help" )
 		usage 
 		exit ;;
+	"--ascii="* )
+		ASCII="${1#--ascii=}"
+		;;
 	"--dbname="* )
 		DBNAME="${1#--dbname=}"
 		;;
@@ -121,8 +126,16 @@ cd $DBFARM
 
 echo "Checkpoint store $CHKPNTDIR"
 echo "Preparing checkpoint file '$DBNAME/$TAG'"
-tar -cf $CHKPFILE.tar $DBNAME || die "Creation of checkpoint file failed"
-gzip $CHKPFILE.tar || die "Compression of checkpoint file failed"
+if [ "$ASCII" = "yes" ]
+then
+	monetdb --start --dbname=$DBNAME
+	sleep 2
+	MapiClient -lsql --dump >$CHKPFILE.sql || dies "Creation of dump failed"
+	gzip $CHKPFILE.sql || die "Compression of dump file failed"
+else
+	tar -cf $CHKPFILE.tar $DBNAME || die "Creation of checkpoint file failed"
+	gzip $CHKPFILE.tar || die "Compression of checkpoint file failed"
+fi
 
 cd $DBLOGS
 echo "Preparing checkpoint log file '$DBNAME/$TAG-logs'"
@@ -133,4 +146,3 @@ then
 fi
 tar -cf $LOGFILE.tar $DBNAME || die "Creation of checkpoint log file failed"
 gzip $LOGFILE.tar || die "Compression of checkpoint log file failed"
-
diff --git a/MonetDB5/src/tools/mrecover b/MonetDB5/src/tools/mrecover
--- a/MonetDB5/src/tools/mrecover
+++ b/MonetDB5/src/tools/mrecover
@@ -21,6 +21,7 @@ function usage()
 {
 	echo "Usage: mrecover [options] "
 	echo "    --dbname=<database_name>"
+	echo "    --ascii=<yes/no> default no"
 	echo "    --chkpnt=<directory>"
 	echo "    --help"
 }
@@ -46,12 +47,16 @@ fi
 
 # massage the argument list to prepare for calling
 DBNAME=""
+ASCII="no"
 while [ $# -gt 0 ]
 do
 	case "$1" in
 	 "--help" )
 		usage 
 		exit ;;
+	"--ascii="* )
+		ASCII="${1#--ascii=}"
+		;;
 	"--dbname="* )
 		DBNAME="${1#--dbname=}"
 		;;
@@ -144,9 +149,17 @@ fi
 cd $DBFARM
 echo "Restore from store $CHKPNTDIR"
 echo "Reload checkpoint file '$DBNAME/$TAG.tar'"
-gunzip $CHKPFILE.tar.gz || die "Decompression of checkpoint file failed"
-tar -xf $CHKPFILE.tar $DBNAME || die "Extraction of checkpoint file failed"
-gzip $CHKPFILE.tar || die "Compression of checkpoint file failed"
+if [ $ASCII = "yes" ]
+then
+	monetdb --start --dbname=$DBNAME
+	gunzip $CHKPFILE.sql.gz || die "Decompression of dump file failed"
+	MapiClient -lsql $CHKPFILE.sql || dies "Could not reload dump file"
+	gzip $CHKPFILE.sql || die "Compression of dump file failed"
+else
+	gunzip $CHKPFILE.tar.gz || die "Decompression of checkpoint file failed"
+	tar -xf $CHKPFILE.tar $DBNAME || die "Extraction of checkpoint file failed"
+	gzip $CHKPFILE.tar || die "Compression of checkpoint file failed"
+fi
 
 cd $DBLOGS
 echo "Reload checkpoint log file '$DBNAME/$TAG-logs.tar'"
