(hopefully) fixing "make check" for monet5

diff --git a/MonetDB5/RunMtest.in b/MonetDB5/RunMtest.in
--- a/MonetDB5/RunMtest.in
+++ b/MonetDB5/RunMtest.in
@@ -1,15 +1,43 @@
 #!/bin/sh
 
-builddir=@QMONETDB_BUILD@
+# The contents of this file are subject to the MonetDB Public
+# License Version 1.0 (the "License"); you may not use this file
+# except in compliance with the License. You may obtain a copy of
+# the License at
+# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
+#
+# Software distributed under the License is distributed on an "AS
+# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
+# implied. See the License for the specific language governing
+# rights and limitations under the License.
+#
+# The Original Code is the Monet Database System.
+#
+# The Initial Developer of the Original Code is CWI.
+# Portions created by CWI are Copyright (C) 1997-2004 CWI.
+# All Rights Reserved.
+#
+# Contributor(s):
+#		Martin Kersten <Martin.Kersten@cwi.nl>
+#		Peter Boncz <Peter.Boncz@cwi.nl>
+#		Niels Nes <Niels.Nes@cwi.nl>
+#		Stefan Manegold  <Stefan.Manegold@cwi.nl>
+
+builddir=`pwd`
 # make sure srcdir contains absolute path name
 srcdir=`cd '@srcdir@'; pwd`
 uname=`uname`
 
-# where compiled modules are to be found
-MOD_PATH="${builddir}/src/modules/atoms/.libs:${builddir}/src/modules/kernel/.libs:${builddir}/src/modules/mal/.libs"
+MONETDB_PREFIX=@MONETDB_PREFIX@
 
-#where module init scripts are to be found
-#MAL_PATH="${builddir}/src/modules"
+if [ ! -x "${MONETDB_PREFIX}/bin/Mtest.py" ]
+then
+	echo "Mtest.py not found, install MonetDB first" >&2
+	exit 1
+fi
+
+# where compiled modules are to be found
+MOD_PATH="${builddir}/src/modules/atoms/.libs:${builddir}/src/modules/kernel/.libs:${builddir}/src/modules/mal/.libs:${MONETDB_PREFIX}/lib/MonetDB"
 
 if [ "${LD_LIBRARY_PATH}" ] ; then
 	LD_LIBRARY_PATH=":${LD_LIBRARY_PATH}"
@@ -22,9 +50,8 @@ if [ "${uname}" = "AIX"  -a  "${LIBPATH}" ] ; then
 fi
 
 # enhance various paths to find our stuff
-PATH="${builddir}/src/testing:${builddir}/src/tools:${builddir}/src/mil:${builddir}/src/mapi/clients/C:${builddir}/src/mapi/clients/python:$PATH"
-PYTHONPATH="${builddir}/src/testing:${srcdir}/src/testing:${builddir}/src/common:${srcdir}/src/mapi/clients/python"
-libpath="${MOD_PATH}:${builddir}/src/common/.libs:${builddir}/src/gdk/.libs:${builddir}/src/mal/.libs:${builddir}/src/mapi/clients/C/.libs"
+PATH="${builddir}/src/tools:${builddir}/src/mil:${MONETDB_PREFIX}/bin:$PATH"
+libpath="${MOD_PATH}:${builddir}/src/mal/.libs"
 LD_LIBRARY_PATH="${libpath}${LD_LIBRARY_PATH}"
 if [ "${uname}" = "Darwin" ] ; then
 	DYLD_LIBRARY_PATH="${libpath}${DYLD_LIBRARY_PATH}"
@@ -34,7 +61,7 @@ if [ "${uname}" = "AIX" ] ; then
 	LIBPATH="${libpath}${LIBPATH}"
 	export LIBPATH
 fi
-export PATH PYTHONPATH LD_LIBRARY_PATH
+export PATH LD_LIBRARY_PATH
 
 # execute Mtest.py in the source directory
 cd "$srcdir"
@@ -45,5 +72,4 @@ python -V
 
 # execute the script
 # if no arguments, do a recursive test (Mtest.py -r), else pass on the arguments
-exec python "${builddir}/src/testing/Mtest.py" --monet_mod_path="${MOD_PATH}" --config="${builddir}/conf/MonetDB5.conf" --dbfarm="${builddir}/dbfarm" --sql_logdir="${builddir}/log" --TSTTRGBASE="${builddir}" "${@--r}"
-#--monet_mal_path="${MAL_PATH}"
+exec Mtest.py --monet_mod_path="${MOD_PATH}" --TSTSRCBASE="$srcdir" --TSTBLDBASE="$builddir" --TSTTRGBASE="${builddir}" --config="${builddir}/conf/MonetDB5.conf" --dbfarm="${builddir}/dbfarm" --sql_logdir="${builddir}/log" "${@--r}"
